# Generated by Django 4.2.2 on 2023-07-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SorteoTique", "0002_remove_client_pwd_remove_client_pwd_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="seller_region",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
