# Generated by Django 4.2.2 on 2023-07-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Winner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("draw", models.CharField(max_length=30)),
                ("prize", models.CharField(max_length=30)),
            ],
        ),
    ]
